// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-fTHZhPdJ-5T0X1F53POqCg8XRNS9bE',
    appId: '1:934172208919:web:661eda330a838ae431d152',
    messagingSenderId: '934172208919',
    projectId: 'umpsa-care',
    authDomain: 'umpsa-care.firebaseapp.com',
    databaseURL: 'https://umpsa-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umpsa-care.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbHDJfsLLKT6wQXWz_Th1o3mnmWlNDk4',
    appId: '1:934172208919:android:57caf1f6d2af94c631d152',
    messagingSenderId: '934172208919',
    projectId: 'umpsa-care',
    databaseURL: 'https://umpsa-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umpsa-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3hWqXmnCamf0zqEUkQaZHcaTDqzmKQE',
    appId: '1:934172208919:ios:b32d2a567842517b31d152',
    messagingSenderId: '934172208919',
    projectId: 'umpsa-care',
    databaseURL: 'https://umpsa-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umpsa-care.firebasestorage.app',
    iosBundleId: 'com.example.umpsaCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3hWqXmnCamf0zqEUkQaZHcaTDqzmKQE',
    appId: '1:934172208919:ios:b32d2a567842517b31d152',
    messagingSenderId: '934172208919',
    projectId: 'umpsa-care',
    databaseURL: 'https://umpsa-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umpsa-care.firebasestorage.app',
    iosBundleId: 'com.example.umpsaCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL-fTHZhPdJ-5T0X1F53POqCg8XRNS9bE',
    appId: '1:934172208919:web:adead860839675e831d152',
    messagingSenderId: '934172208919',
    projectId: 'umpsa-care',
    authDomain: 'umpsa-care.firebaseapp.com',
    databaseURL: 'https://umpsa-care-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'umpsa-care.firebasestorage.app',
  );
}
